package agencia_viajes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
import java.io.*;
import javax.swing.JOptionPane;
public class Csesion extends javax.swing.JFrame {

    /**
     * Creates new form Csesion
     */
    public Csesion() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTtel = new javax.swing.JTextField();
        jTdir = new javax.swing.JTextField();
        jTcorreo = new javax.swing.JTextField();
        jBace = new javax.swing.JButton();
        jBexit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTcontra1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTcontra2 = new javax.swing.JTextField();
        jCedad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Edad:");

        jLabel3.setText("tel:");

        jLabel4.setText("Dirección: ");

        jLabel5.setText("Correo:");

        jBace.setText("Aceptar");
        jBace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaceActionPerformed(evt);
            }
        });

        jBexit.setText("Salir");
        jBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexitActionPerformed(evt);
            }
        });

        jLabel6.setText("Contraseña:");

        jLabel7.setText("Confirmar Contraseña:");

        jCedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", " " }));
        jCedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCedadActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Crear Sesión");

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(79, 79, 79))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTcontra1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTcorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTdir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTtel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTcontra2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBace)))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBexit)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcontra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTcontra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBace)
                        .addComponent(jButton1))
                    .addComponent(jBexit))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCedadActionPerformed

    private void jTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreActionPerformed

    }//GEN-LAST:event_jTnombreActionPerformed

    private void jBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexitActionPerformed
        System.exit(0);
        try{
            FileInputStream fis = new FileInputStream("Clientes.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            Cliente clientes2[]= (Cliente[]) ois.readObject();
            ois.close();
            int el=0,c=0;
            for(int i=0; i<clientes2.length; i++){
                if(clientes2[i].getactivo()==1){
                    c=i;
                }
            }
            clientes2[c].editaract();
            FileOutputStream fs = new FileOutputStream("Clientes.txt");
            ObjectOutputStream os = new ObjectOutputStream(fs);
            os.writeObject(clientes2);
            os.close();
        } catch(Exception e) { e.printStackTrace(); }
    }//GEN-LAST:event_jBexitActionPerformed

    private void jBaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaceActionPerformed

        String name=jTnombre.getText();
        String ed= (String)jCedad.getSelectedItem();
        int edad = Integer.parseInt(ed);
        String tel=jTtel.getText();
        String dir=jTdir.getText();
        String correo=jTcorreo.getText();
        String contra1=jTcontra1.getText();
        String contra2=jTcontra2.getText();
        Cliente C1=new Cliente(name,edad,tel,dir,correo,contra1);
        Cliente C2=new Cliente(name,edad,dir,correo,contra1);
        C1.crearNum(1);
        System.out.println(C1);
        Cliente clientes[]={C1};
        try {
            File archivo = new File("Clientes.txt");
            if (!archivo.exists()) {
                if(contra1.equals(contra2)){
                    try {
                        FileOutputStream fs = new FileOutputStream("Clientes.txt");
                        ObjectOutputStream os = new ObjectOutputStream(fs);
                        os.writeObject(clientes);
                        os.close();
                    } catch(Exception e) { e.printStackTrace(); }
                    JOptionPane.showMessageDialog(this,"Perfil creado Exitosamente");
                }else{
                    int i=JOptionPane.showConfirmDialog(this,"Lo siento, las contraseñas no coinciden \n Quieres intentar de nuevo?");
                    if(i==1||i==2){
                        Isesion Is=new Isesion();
                        Is.setVisible(true);
                        dispose();
                    }
                }
            }else{
                FileInputStream fis = new FileInputStream("Clientes.txt");
                ObjectInputStream ois = new ObjectInputStream(fis);
                Cliente clientes2[]= (Cliente[]) ois.readObject( );
                ois.close();
                int el=0;
                for(int i=0; i<clientes2.length; i++){
                    if((clientes2[i].obtenerNombre().equals(C1.obtenerNombre()))||(clientes2[i].obtenerCorreo().equals(C1.obtenerCorreo()))){
                        el++;
                    }
                    System.out.println(el);
                }
                if(el>0){
                    int j=JOptionPane.showConfirmDialog(this,"Usuario existente \n Quieres intentar de nuevo?");
                    if(j==1||j==2){
                        Isesion Is=new Isesion();
                        Is.setVisible(true);
                        dispose();
                    }
                }else{
                    if(contra1.equals(contra2)){
                        try {
                            C1.crearNum(clientes2.length+1);
                            Cliente[] c3 = new Cliente[clientes2.length+1];
                            for(int e=0; e<clientes2.length; e++){
                                c3[e]=clientes2[e];
                            }
                            c3[clientes2.length]=C1;
                            System.out.println("Aqui nos muestra como es c3");
                            for(int e=0; e<c3.length; e++){
                                System.out.println(c3[e]);
                            }
                            FileOutputStream fs = new FileOutputStream("Clientes.txt");
                            ObjectOutputStream os = new ObjectOutputStream(fs);
                            os.writeObject(c3);
                            os.close();
                        } catch(Exception e) { e.printStackTrace(); }
                        JOptionPane.showMessageDialog(this,"Perfil creado Exitosamente");
                    }else{
                        int y=JOptionPane.showConfirmDialog(this,"Lo siento, las contraseñas no coinciden \n Quieres intentar de nuevo?");
                        if(y==1||y==2){
                            Isesion Is=new Isesion();
                            Is.setVisible(true);
                            dispose();
                        }
                    }
                }
            }
        } catch(Exception e) { e.printStackTrace(); }
        Isesion Is=new Isesion();
        Is.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBaceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Isesion Is=new Isesion();
        Is.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Csesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Csesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Csesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Csesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Csesion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBace;
    private javax.swing.JButton jBexit;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCedad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTcontra1;
    private javax.swing.JTextField jTcontra2;
    private javax.swing.JTextField jTcorreo;
    private javax.swing.JTextField jTdir;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTtel;
    // End of variables declaration//GEN-END:variables
}
