/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia_viajes;

/**
 *
 * @author erikg
 */

import java.io.*;
import javax.swing.*;
import java.awt.*;
import agencia_viajes.*;
import javax.activation.*;
import javax.mail.*;
import java.util.*;

import javax.mail.internet.*;



public class editCliente extends javax.swing.JFrame {
    byte[] fileBytes=Sesion.getUsuarioActual().getImagen();

    /**
     * Creates new form editCliente
     */
    public editCliente() {
        initComponents();
        jTnombre.setText(Sesion.getUsuarioActual().obtenerNombre());
        jCedad.setSelectedIndex(Sesion.getUsuarioActual().getEdad()-18);
        System.out.println(Sesion.getUsuarioActual().getEdad());
        jTtel.setText(Sesion.getUsuarioActual().getTel());
        jTdir.setText(Sesion.getUsuarioActual().getDireccion());
        jTcorreo.setText(Sesion.getUsuarioActual().obtenerCorreo());
        ImageIcon imageIcon = new ImageIcon(fileBytes);
        Image image = imageIcon.getImage().getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledImageIcon = new ImageIcon(image);

        jLabel10.setIcon(scaledImageIcon);
        
    }
    public static void transfer_to_email(String correo, String nombre) {
        System.out.println(correo + " " + nombre);
        String correoEnvia = "Aqui va tu correo";
        String contraseña = "Aqui va tu contraseña generada(sin espacios)";
        String mensaje = "Hola " + nombre
                + "tu cuenta ha sido editada correctamente";

        Properties objectPEC = new Properties();
        objectPEC.put("mail.smtp.host", "smtp.gmail.com");
        objectPEC.setProperty("mail.smtp.starttls.enable", "true");
        objectPEC.put("mail.smtp.port", "587");
        objectPEC.setProperty("mail.smtp.port", "587");
        objectPEC.put("mail.smtp.user", correoEnvia);
        objectPEC.setProperty("mail.smtp.auth", "true");

        Session sesion = Session.getDefaultInstance(objectPEC);
        MimeMessage mail = new MimeMessage(sesion);

        try {
            mail.setFrom(new InternetAddress(correoEnvia));
            mail.addRecipient(Message.RecipientType.TO, new InternetAddress(correo));
            mail.setSubject("Se creo tu cuenta correctamente");
            mail.setText(mensaje);

            Transport transporte = sesion.getTransport("smtp");
            transporte.connect(correoEnvia, contraseña);
            transporte.sendMessage(mail, mail.getRecipients(Message.RecipientType.TO));
            transporte.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jBexit = new javax.swing.JButton();
        jTnombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCedad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTcontra1 = new javax.swing.JPasswordField();
        jTtel = new javax.swing.JTextField();
        jTcontra2 = new javax.swing.JPasswordField();
        jTdir = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTcorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBace = new javax.swing.JButton();
        jTcontra3 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame.getContentPane());
        frame.getContentPane().setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBexit.setText("Cerrar");
        jBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexitActionPerformed(evt);
            }
        });

        jTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreActionPerformed(evt);
            }
        });

        jLabel6.setText("Contraseña actual:");

        jLabel1.setText("Nombre:");

        jLabel7.setText("Nueva Contraseña:");

        jLabel2.setText("Edad:");

        jCedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", " " }));
        jCedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCedadActionPerformed(evt);
            }
        });

        jLabel3.setText("tel:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Editar Sesión");

        jLabel4.setText("Dirección: ");

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Correo:");

        jButton2.setText("Elegir...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Imagen de perfil");

        jBace.setText("Aceptar");
        jBace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaceActionPerformed(evt);
            }
        });

        jLabel11.setText("Confirmar Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jBexit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBace)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(51, 51, 51))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTcorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTdir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTtel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jCedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTcontra2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                        .addComponent(jTcontra1, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(jTcontra3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTcontra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTcontra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcontra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBace)
                        .addComponent(jButton1))
                    .addComponent(jBexit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexitActionPerformed
        Sesion.cerrarSesion();
        System.exit(0);
    }//GEN-LAST:event_jBexitActionPerformed

    private void jTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreActionPerformed

    }//GEN-LAST:event_jTnombreActionPerformed

    private void jCedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCedadActionPerformed
    private static byte[] convertFileToByteArray(File file) throws IOException {
        FileInputStream fis = new FileInputStream(file);
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        byte[] buf = new byte[1024];

        try {
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
        } finally {
            fis.close();
            bos.close();
        }

        return bos.toByteArray();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio In=new Inicio();
        In.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        // Mostrar el diálogo de selección de archivo
        int result = fileChooser.showOpenDialog(frame);
        // Verificar si el usuario seleccionó un archivo
        if (result == JFileChooser.APPROVE_OPTION) {
        // Obtener el archivo seleccionado
            File selectedFile = fileChooser.getSelectedFile();
            try {
                // Convertir el archivo a un array de bytes
                fileBytes = convertFileToByteArray(selectedFile);
                ImageIcon imageIcon = new ImageIcon(fileBytes);
                Image image = imageIcon.getImage().getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledImageIcon = new ImageIcon(image);
                
                jLabel10.setIcon(scaledImageIcon);
                // Hacer algo con el array de bytes, como enviarlo a una base de datos o procesarlo de alguna manera
                System.out.println(fileBytes);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaceActionPerformed
        String name=jTnombre.getText();
        String ed= (String)jCedad.getSelectedItem();
        int edad = Integer.parseInt(ed);
        String tel=jTtel.getText();
        String dir=jTdir.getText();
        String correo=jTcorreo.getText();
        String patronCorreo = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        String patronContrasena = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";
        
        
        //Contraseñas
        char[] contraChars1 = jTcontra1.getPassword();
        String contra1 = new String(contraChars1);
        char[] contraChars2 = jTcontra2.getPassword();
        String contra2 = new String(contraChars2);
        char[] contraChars3 = jTcontra3.getPassword();
        String contra3 = new String(contraChars3);
       
        
        
        if(contra1.equals(Sesion.getUsuarioActual().obtenerContra())){
            if(contra2.isEmpty()&&contra3.isEmpty()){
                if(correo.matches(patronCorreo)){
                    try {
                        Cliente C1=new Cliente(name,edad,tel,dir,correo,Sesion.getUsuarioActual().obtenerContra(),fileBytes);
                        FileInputStream fis = new FileInputStream("Clientes.txt");
                        ObjectInputStream ois = new ObjectInputStream(fis);
                        Cliente clientes2[]= (Cliente[]) ois.readObject( );
                        ois.close();
                        
                        FileInputStream fis1 = new FileInputStream("Admins.txt");
                        ObjectInputStream ois1 = new ObjectInputStream(fis1);
                        Admin admins2[]= (Admin[]) ois1.readObject( );
                        ois1.close();
                        int c=0;
                        
                        for(int j=0;j<admins2.length;j++){
                            if(admins2[j].getCorreo().equals(correo)){
                                c++;
                            }
                        }
                        if(c==0){
                            for(int i=0; i<clientes2.length; i++){
                                if(!(clientes2[i].obtenerCorreo().equals(Sesion.getUsuarioActual().obtenerCorreo()))){
                                    if(clientes2[i].obtenerCorreo().equals(correo)){
                                        c++;
                                    }
                                }
                            }
                            if(c==0){
                                for(int i=0; i<clientes2.length; i++){
                                    if((clientes2[i].obtenerCorreo().equals(Sesion.getUsuarioActual().obtenerCorreo()))){
                                        clientes2[i]=C1;
                                    }
                                }
                                FileOutputStream fos = new FileOutputStream("Clientes.txt");
                                ObjectOutputStream ous = new ObjectOutputStream(fos);
                                ous.writeObject(clientes2);
                                ous.close();
                                JOptionPane.showMessageDialog(this,"Perfil editado Exitosamente");
                                transfer_to_email(Sesion.getUsuarioActual().obtenerCorreo(),Sesion.getUsuarioActual().obtenerNombre());
                                Sesion.cerrarSesion();
                                Isesion Is=new Isesion();
                                Is.setVisible(true);
                                dispose();
                            }else{
                                int i=JOptionPane.showConfirmDialog(this,"Correo en uso \n Quieres intentar de nuevo?");
                                if(i==1||i==2){
                                    InicioAdmin IA=new InicioAdmin();
                                    IA.setVisible(true);
                                    dispose();
                                }
                            }
                        }else{
                            int i=JOptionPane.showConfirmDialog(this,"Correo en uso \n Quieres intentar de nuevo?");
                            if(i==1||i==2){
                                InicioAdmin IA=new InicioAdmin();
                                IA.setVisible(true);
                                dispose();
                            }
                        }
                        
                    } catch(Exception e) { e.printStackTrace(); }
                }else{
                    int i=JOptionPane.showConfirmDialog(this,"Lo siento, ese no es un correo valido \n Quieres intentar de nuevo?");
                    if(i==1||i==2){
                        Inicio In=new Inicio();
                        In.setVisible(true);
                        dispose();
                    }
                }
            }else if(contra2.matches(patronContrasena)){
                if(contra2.equals(contra3)){
                    if(correo.matches(patronCorreo)){
                        Cliente C1=new Cliente(name,edad,tel,dir,correo,contra2,fileBytes);
                        try {
                            FileInputStream fis = new FileInputStream("Clientes.txt");
                            ObjectInputStream ois = new ObjectInputStream(fis);
                            Cliente clientes2[]= (Cliente[]) ois.readObject( );
                            ois.close();

                            FileInputStream fis1 = new FileInputStream("Admins.txt");
                            ObjectInputStream ois1 = new ObjectInputStream(fis1);
                            Admin admins2[]= (Admin[]) ois1.readObject( );
                            ois1.close();
                            int c=0;

                            for(int j=0;j<admins2.length;j++){
                                if(admins2[j].getCorreo().equals(correo)){
                                    c++;
                                }
                            }
                            if(c==0){
                                for(int i=0; i<clientes2.length; i++){
                                    if(!(clientes2[i].obtenerCorreo().equals(Sesion.getUsuarioActual().obtenerCorreo()))){
                                        if(clientes2[i].obtenerCorreo().equals(correo)){
                                            c++;
                                        }
                                    }
                                }
                                if(c==0){
                                    for(int i=0; i<clientes2.length; i++){
                                        if((clientes2[i].obtenerCorreo().equals(Sesion.getUsuarioActual().obtenerCorreo()))){
                                            clientes2[i]=C1;
                                        }
                                    }
                                    FileOutputStream fos = new FileOutputStream("Clientes.txt");
                                    ObjectOutputStream ous = new ObjectOutputStream(fos);
                                    ous.writeObject(clientes2);
                                    ous.close();
                                    JOptionPane.showMessageDialog(this,"Perfil editado Exitosamente");
                                    Sesion.cerrarSesion();
                                    Isesion Is=new Isesion();
                                    Is.setVisible(true);
                                    dispose();
                                }else{
                                    int i=JOptionPane.showConfirmDialog(this,"Correo en uso \n Quieres intentar de nuevo?");
                                    if(i==1||i==2){
                                        InicioAdmin IA=new InicioAdmin();
                                        IA.setVisible(true);
                                        dispose();
                                    }
                                }
                            }else{
                                int i=JOptionPane.showConfirmDialog(this,"Correo en uso \n Quieres intentar de nuevo?");
                                if(i==1||i==2){
                                    InicioAdmin IA=new InicioAdmin();
                                    IA.setVisible(true);
                                    dispose();
                                }
                            }
                        
                        } catch(Exception e) { e.printStackTrace(); }
                    }else{
                        int i=JOptionPane.showConfirmDialog(this,"Lo siento, ese no es un correo valido \n Quieres intentar de nuevo?");
                        if(i==1||i==2){
                            Inicio In=new Inicio();
                            In.setVisible(true);
                            dispose();
                        }
                    }
                }else{
                    int i=JOptionPane.showConfirmDialog(this,"Lo siento, las contraseñas no coinciden \n Quieres intentar de nuevo?");
                    if(i==1||i==2){
                        Inicio In=new Inicio();
                        In.setVisible(true);
                        dispose();
                    }
                }  
            }else{
                int i=JOptionPane.showConfirmDialog(this,"Lo siento, Tu contraseña debe tener al menos una letra, un digito, un caracter especial @, $, !, %, *, ?, & y 8 caracteres \n Quieres intentar de nuevo?");
                if(i==1||i==2){
                    Inicio In=new Inicio();
                    In.setVisible(true);
                    dispose();
                }
            }
        }else{
            int i=JOptionPane.showConfirmDialog(this,"Lo siento, esa no es tu contraseña \n Quieres intentar de nuevo?");
            if(i==1||i==2){
                Inicio In=new Inicio();
                In.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_jBaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame frame;
    private javax.swing.JButton jBace;
    private javax.swing.JButton jBexit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCedad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jTcontra1;
    private javax.swing.JPasswordField jTcontra2;
    private javax.swing.JPasswordField jTcontra3;
    private javax.swing.JTextField jTcorreo;
    private javax.swing.JTextField jTdir;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTtel;
    // End of variables declaration//GEN-END:variables
}
