package agencia_viajes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
import java.io.*;
import javax.swing.*;
import javax.activation.*;
import javax.mail.*;
import java.util.*;

import javax.mail.internet.*;
import agencia_viajes.Sesion;
public class Isesion extends javax.swing.JFrame {

    /**
     * Creates new form Isesion
     */
    public Isesion() {
        initComponents();
    }
    public static void transfer_to_email(String correo, String nombre, String pass) {
        System.out.println(correo + " " + nombre);
        String correoEnvia = "Aqui va tu correo";
        String contraseña = "Aqui va tu contraseña generada(sin espacios)";
        String mensaje = "Hola " + nombre
                + " tu password es: "+pass;

        Properties objectPEC = new Properties();
        objectPEC.put("mail.smtp.host", "smtp.gmail.com");
        objectPEC.setProperty("mail.smtp.starttls.enable", "true");
        objectPEC.put("mail.smtp.port", "587");
        objectPEC.setProperty("mail.smtp.port", "587");
        objectPEC.put("mail.smtp.user", correoEnvia);
        objectPEC.setProperty("mail.smtp.auth", "true");

        Session sesion = Session.getDefaultInstance(objectPEC);
        MimeMessage mail = new MimeMessage(sesion);

        try {
            mail.setFrom(new InternetAddress(correoEnvia));
            mail.addRecipient(Message.RecipientType.TO, new InternetAddress(correo));
            mail.setSubject("Envio de datos");
            mail.setText(mensaje);

            Transport transporte = sesion.getTransport("smtp");
            transporte.connect(correoEnvia, contraseña);
            transporte.sendMessage(mail, mail.getRecipients(Message.RecipientType.TO));
            transporte.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTcorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBcancel = new javax.swing.JButton();
        jBaceptar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTcont = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Correo:");

        jLabel3.setText("Contraseña:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Iniciar Sesión");

        jBcancel.setText("Salir");
        jBcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelActionPerformed(evt);
            }
        });

        jBaceptar.setText("Aceptar");
        jBaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaceptarActionPerformed(evt);
            }
        });

        jButton1.setText("Registrarme");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Recuperar contraseña");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jBcancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46)
                .addComponent(jBaceptar)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTcont, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(169, 169, 169))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(177, 177, 177))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(178, 178, 178))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(153, 153, 153))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTnom, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(136, 136, 136))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcancel)
                    .addComponent(jBaceptar)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBcancelActionPerformed

    private void jBaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaceptarActionPerformed
        String name=jTnom.getText();
        String correo=jTcorreo.getText();
        char[] contraChars = jTcont.getPassword();
        String contra = new String(contraChars);
        
        
        Cliente C1=new Cliente(name,correo,contra);
        try{
            FileInputStream fis = new FileInputStream("Clientes.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            Cliente clientes2[]= (Cliente[]) ois.readObject( );
            ois.close();
            int el=0,c=0;
            for(int i=0; i<clientes2.length; i++){
                if((clientes2[i].obtenerNombre().equals(C1.obtenerNombre()))&&(clientes2[i].obtenerCorreo().equals(C1.obtenerCorreo()))&&(clientes2[i].obtenerContra().equals(C1.obtenerContra()))){
                    el++;
                    c=i;
                    Sesion.setUsuarioActual(clientes2[i]);
                }
            }
            System.out.println(el);
            if(el==1){
                System.out.println("Sesion iniciada");
                JOptionPane.showMessageDialog(this,"Sesion Iniciada \n bienvenido"); 
                clientes2[c].editaract();
                try {
                    FileOutputStream fs = new FileOutputStream("Clientes.txt");
                    ObjectOutputStream os = new ObjectOutputStream(fs);
                    os.writeObject(clientes2);
                    os.close();
                } catch(Exception e) { e.printStackTrace(); }
                Inicio In=new Inicio();
                In.setVisible(true);
                dispose();
            }else{
                Admin admin=new Admin(name,correo,contra);
                try{
                    FileInputStream fis1 = new FileInputStream("Admins.txt");
                    ObjectInputStream ois1 = new ObjectInputStream(fis1);
                    Admin admins2[]= (Admin[]) ois1.readObject( );
                    ois1.close();
                    int e=0;
                    for(int i=0; i<admins2.length; i++){
                        if((admins2[i].getNombre().equals(admin.getNombre()))&&(admins2[i].getCorreo().equals(admin.getCorreo()))&&(admins2[i].getContra().equals(admin.getContra()))){
                            e++;
                            sesionAdmin.setUsuarioActual(admins2[i]);
                        }
                    }
                    System.out.println(el);
                    if(e==1){
                        System.out.println("Sesion iniciada");
                        JOptionPane.showMessageDialog(this,"Sesion Iniciada \n bienvenido"); 
                        try {
                            FileOutputStream fs1 = new FileOutputStream("Admins.txt");
                            ObjectOutputStream os1 = new ObjectOutputStream(fs1);
                            os1.writeObject(admins2);
                            os1.close();
                        } catch(Exception ex) { ex.printStackTrace(); }
                        InicioAdmin IA=new InicioAdmin();
                        IA.setVisible(true);
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this,"Lo siento, valores incorrectos"); 
                }
                }catch(Exception e) { e.printStackTrace(); }
        }} catch(Exception e) { e.printStackTrace(); }
    }//GEN-LAST:event_jBaceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Csesion Cs=new Csesion();
        Cs.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String correo = JOptionPane.showInputDialog("Escribe tu correo \nSe enviara un correo con tu contraseña");
	try {
            FileInputStream fis = new FileInputStream("Clientes.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            Cliente clientes2[]= (Cliente[]) ois.readObject( );
            ois.close();
            int c=0;
            for(int i=0; i<clientes2.length; i++){
                if(clientes2[i].obtenerCorreo().equals(correo)){
                    transfer_to_email(correo,clientes2[i].obtenerNombre(),clientes2[i].obtenerContra());
                    c++;
                }
            }
            if(c==0){
                FileInputStream fis1 = new FileInputStream("Admins.txt");
                ObjectInputStream ois1 = new ObjectInputStream(fis1);
                Admin admins2[]= (Admin[]) ois1.readObject( );
                ois1.close();
                for(int i=0; i<admins2.length; i++){
                    if(admins2[i].getCorreo().equals(correo)){
                        transfer_to_email(correo,admins2[i].getNombre(),admins2[i].getContra());
                    }
                }
            }
        } catch (Exception e) { e.printStackTrace(); }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Isesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Isesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Isesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Isesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Isesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBaceptar;
    private javax.swing.JButton jBcancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jTcont;
    private javax.swing.JTextField jTcorreo;
    private javax.swing.JTextField jTnom;
    // End of variables declaration//GEN-END:variables
}
