/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia_viajes;

import java.io.*;
import javax.swing.*;
import agencia_viajes.*;

/**
 *
 * @author HP
 */
public class Meterdin extends javax.swing.JFrame {
    /**
     * Creates new form Meterdin
     */
    public Meterdin() {
        initComponents();
        SpinnerNumberModel n = new SpinnerNumberModel();
        n.setMaximum(50000);
        n.setMinimum(0);
        jSdinero.setModel(n);
        Cliente Cli=Sesion.getUsuarioActual();
        jTsaldo.setText(String.valueOf(Cli.obtenerCuenta().mostrarS()));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTsaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSdinero = new javax.swing.JSpinner();
        jBacept = new javax.swing.JButton();
        jBcancel = new javax.swing.JButton();
        jAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsaldoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Saldo:");

        jBacept.setText("Aceptar");
        jBacept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaceptActionPerformed(evt);
            }
        });

        jBcancel.setText("Cerrar");
        jBcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelActionPerformed(evt);
            }
        });

        jAtras.setText("Atras");
        jAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBcancel)
                .addGap(63, 63, 63)
                .addComponent(jBacept)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(jTsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSdinero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jSdinero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBacept)
                    .addComponent(jBcancel)
                    .addComponent(jAtras))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsaldoActionPerformed

    private void jBaceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaceptActionPerformed
        Cliente Cli=Sesion.getUsuarioActual();
        Cli.obtenerCuenta().aumeS(Double.parseDouble(jSdinero.getValue()+".0"));
        try{
            FileInputStream fis = new FileInputStream("Clientes.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            Cliente clientes2[]= (Cliente[]) ois.readObject( );
            for(int i=0; i<clientes2.length; i++){
                if(clientes2[i].obtenerCorreo().equals(Cli.obtenerCorreo())){
                    clientes2[i]=Cli;
                    break;
                }
            } 
            FileOutputStream fs = new FileOutputStream("Clientes.txt");
            ObjectOutputStream os = new ObjectOutputStream(fs);
            os.writeObject(clientes2);
            ois.close();
            
        } catch(Exception e) { e.printStackTrace(); }
        
        
        System.out.println(Cli.obtenerCuenta().mostrarS());
        jTsaldo.setText(String.valueOf(Cli.obtenerCuenta().mostrarS()));
        
    }//GEN-LAST:event_jBaceptActionPerformed

    private void jBcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelActionPerformed
        System.exit(0);
        try{
            FileInputStream fis = new FileInputStream("Clientes.txt");
            ObjectInputStream ois = new ObjectInputStream(fis);
            Cliente clientes2[]= (Cliente[]) ois.readObject();
            ois.close();
            int el=0,c=0;
            for(int i=0; i<clientes2.length; i++){
                if(clientes2[i].getactivo()==1){
                    c=i;
                }
            }
            clientes2[c].editaract();
            FileOutputStream fs = new FileOutputStream("Clientes.txt");
            ObjectOutputStream os = new ObjectOutputStream(fs);
            os.writeObject(clientes2);
            os.close();
        } catch(Exception e) { e.printStackTrace(); }
    }//GEN-LAST:event_jBcancelActionPerformed

    private void jAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtrasActionPerformed
        Inicio In=new Inicio();
        In.setVisible(true);
        dispose();
    }//GEN-LAST:event_jAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meterdin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meterdin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meterdin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meterdin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meterdin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAtras;
    private javax.swing.JButton jBacept;
    private javax.swing.JButton jBcancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSdinero;
    private javax.swing.JTextField jTsaldo;
    // End of variables declaration//GEN-END:variables
}
